// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TextServices.Builder.Api.Data;

#nullable disable

namespace TextServices.Builder.Api.Migrations
{
    [DbContext(typeof(BuilderDbContext))]
    [Migration("20260526150122_AddFulfilledServicesToBuilderJob")]
    partial class AddFulfilledServicesToBuilderJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TextServices.Builder.Api.Data.BuilderJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CustomTypesJson")
                        .HasColumnType("text")
                        .HasColumnName("custom_types_json");

                    b.Property<string>("Errors")
                        .HasColumnType("text")
                        .HasColumnName("errors");

                    b.Property<DateTimeOffset?>("Finished")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished");

                    b.Property<int?>("FulfilledServices")
                        .HasColumnType("integer")
                        .HasColumnName("fulfilled_services");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text")
                        .HasColumnName("hangfire_job_id");

                    b.Property<int>("PagesCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("pages_completed");

                    b.Property<int>("Services")
                        .HasColumnType("integer")
                        .HasColumnName("services");

                    b.Property<string>("SourceDataJson")
                        .HasColumnType("text")
                        .HasColumnName("source_data_json");

                    b.Property<string>("SourceUri")
                        .HasColumnType("text")
                        .HasColumnName("source_uri");

                    b.Property<DateTimeOffset?>("Started")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TotalImageCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_image_count");

                    b.Property<int>("TotalPages")
                        .HasColumnType("integer")
                        .HasColumnName("total_pages");

                    b.Property<int>("TotalWordCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_word_count");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.ToTable("jobs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
